guide-messages:
  - "§aBienvenue dans le guide!"
  - "§aTu peux tout personnalisé dans la config de CallOfGuide."
help-messages:
  - "§eVoici l'aide!"
  - "§eTu peux tout personnalisé dans la config de CallOfGuide."
